# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

name: variational
channels:
- conda-forge
- microsoft
dependencies:
  - notebook
  - matplotlib
  - qsharp==0.20.2111176757-sdl
  # This sample uses the QuTiP library to decompose Hamiltonian operators in
  # the Pauli basis.
  - qutip
